version: '2'
services:
  flow_mysql:
    container_name: flow_mysql
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'flow'
      MYSQL_USER: 'flow'
      MYSQL_PASSWORD: 'toor'
      MYSQL_ROOT_PASSWORD: 'toor'
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - flow_mysql_data:/var/lib/mysql
    networks:
      inner:
        aliases:
          - flow_mysql
networks:
  inner: {}
volumes:
  flow_mysql_data: {}

